language: es_es

# Minimum players to start
minPlayers: 4
# Maximum impostors
maxImpostors: 1

# Game locations
locations:
  lobby:
    coords:
      x: 118.5
      y: 39
      z: 388.5
      yaw: -180.0
      pitch: 0.0
  start:
    coords:
      x: 118.5
      y: 34.5
      z: 385.85
      yaw: 0.0
      pitch: 0.0
